<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $name ?> - zapas</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    <!-- <link rel="stylesheet" href="styles/style.css?v=1.1"> -->
    <link rel="stylesheet" href="styles/style.css?=<?= time(); ?>">

    <?php   require_once __DIR__ . '/../app/helper/auth.helper.php';
            AuthHelper::init(); // Inicia la sesión
    ?>
    
</head>
<body>
    
        <header class="nav">

            <nav>
                <ul>
                    <li><a href="home">Home</a></li>
                    <li><a href="producto">Producto</a></li>
                        <?php if(!isset($_SESSION['USER_ID'])){ ?>
                            <li><a href="login">Iniciar Sesion</a></li>
                        <?php } else { ?>
                            <li><a href="perfil">Perfil</a></li>
                        <?php } ?>

                </ul>
            </nav>
    
        </header>
