    <?php require('header.phtml'); ?>

        <div class="fondo">

        <!-- titulo general -->
        <div class="contenedor-titulo">
            <h1>-Zapas-</h1>
        </div>

        <section class="contenedor-general">
    
            <!-- contenedor de las categorias -->
    
            <div class="contenedor-general-categoria">
    
                <div class="contenedor-categoria">
    
                    <div class="contenedor-nombre-categoria">
                        <h2>nombre categoria</h2>
                    </div>
    
                    <div class="contenedor-imagenes">
                        <div class="contenedor-img">
                            <a href="producto">
                                <div class="img"></div>
                            </a>
                        </div>
                        <div class="contenedor-img">
                            <a href="producto"><img src="http://localhost/practicos/zapas/imgs/jordan.png" alt=""></a>
                        </div>
                        <div class="contenedor-img">
                            <a href="producto"><img src="http://localhost/practicos/zapas/imgs/jordan.png" alt=""></a>
                        </div>
                    </div>
                    <?php BASE_URL ?>
                    
                </div>
    
            </div>

        </section>

    </div>
    
</body>
</html>