    <?php require('header.phtml'); ?>

        <div class="fondo">

        <!-- titulo general -->
        <div class="contenedor-titulo">
            <h1>-Zapas-</h1>
        </div>

        <section class="contenedor-general">
    
            <!-- contenedor de las categorias -->
    
            <div class="contenedor-general-categoria">
    
                <div class="contenedor-categoria">
    
                    <div class="contenedor-nombre-categoria">
                        <h2>nombre categoria</h2>
                    </div>
    
                    <div class="contenedor-imagenes">
                        <?php for ($i=0; $i < 3 ; $i++){ ?>
                        <div class="contenedor-img">
                            <a href="producto"><img src="https://imgs.search.brave.com/xUhJbSiO6Z5GUyyKnaZVYjgMjXoTwtUl-4jXXiLPgkE/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMuY2hvbGxvbWV0/cm8uY29tL3RocmVh/ZHMvcmF3LzBnbGgy/LzE0Nzc1NDJfMS9y/ZS83Njh4NzY4L3F0/LzYwLzE0Nzc1NDJf/MS5qcGc" alt=""></a>
                        </div>
                        <?php } ?>
                    </div>
                    <?php BASE_URL ?>
                    
                </div>
    
            </div>

        </section>

    </div>
    
</body>
</html>