    <?php  require('header.phtml') ?>

    <div class="fondo">

                <div class="contenedor-form">

                        <!-- seccion del formulario -->

                        <section class="formulario-login">

                            <h1>Login</h1>

                            <form action="loginUsuario" method="POST">
                                
                                <div class="contenedor-parte-principal-login">
                                    
                                    <div class="usuario-contrasenia">
                                        <label for="">Nombre Usuario</label>
                                        <input type="text" name="usr" required>
    
                                        <label for="">Contraseña</label>
                                        <input type="password" name="pass" id="" required>
                                    </div>
                                    
                                </div>

                                <div class="contenedor-envio">
                                    <input type="submit" value="enviar">
                                </div>

                            </form>

                            <div class="contenedor-a">
                                <a href="register">No estoy Registrado</a>
                            </div>

                        </section>

            </div>

            <?php if ($error): ?>
                    <div class="container-error">
                    <div class="error">
                        <?= $error ?>
                    </div>
                    </div>
            <?php endif ?>  

    </div>

</body>
</html>