    <?php require_once 'templates/header.phtml' ?>

    
    <div class="fondo">

    <section class="principal">

        <div class="cont-info">
            <div class="cont-info-img">
                <div class="img">
                    <img src="" alt="">
                </div>
            </div>
            <div class="info">
                <h2><?= htmlspecialchars($_SESSION['USER_NAME']) ?></h2>
                <?php if(!isset($_SESSION['USER_MAIL'])){?>
                <p><?= htmlspecialchars($mail) ?></p>
                <?php } else { ?>
                <p><?= htmlspecialchars('mail') ?></p>
                <?php } ?>

            </div>
        </div>

        <div class="cont-compras">
            <div class="titulo">
                <h3>- compras -</h3>
            </div>
            <div class="compras">
                <img src="" alt="">
                <img src="" alt="">
                <img src="" alt="">
            </div>
        </div>

        <div class="cont-logout">
            <button><a href="logout">Logout</a></button>
        </div>

    </section>
</div>

</body>
</html>