    <?php require('templates/header.phtml'); ?>
    
    <div class="fondo">

        <div class="contenedor">

            <div class="contenedor-producto">

                <div class="titulo">
                    <h1>-Zapas-</h1>
                </div>
    
                <div class="contenedor-grid">
                    <div class="contenedor-separador">

                        <div class="contenedor-imagen">
                            <!-- <img src="imgs/jordan.webp" alt=""> -->
                        </div>
            
                        <div class="contenedor-detalles">
            
                            <div class="contenedor-interno-detalles">
                                <div class="detalles">
                                    <h2>Jordan</h2>
                                    <p>Talle: XL</p>
                                    <p>299$</p>
                                    <div class="comprar">
                                        <button class="btn-comprar">Comprar</button>
                                        <button class="btn-guardar"><i class="fa-regular fa-bookmark"></i></button>
                                    </div>
                                </div>
                
                                
                            </div>
            
                        </div>
    
                    </div>
                </div>
    
            </div>

        </div>

    </div>

</body>
</html>